spring.datasource.url=jdbc:mysql://localhost:3306/micromarket
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080
server.servlet.context-path=/api/v1

security.jwt.secret-key=pF+HxjF3FgXlI5nAzC/Nt+mv1T7PmZbOYfWcy6snYqE=
security.jwt.token-expiration=600000