spring.datasource.url=jdbc:mysql://localhost:3306/micromarket
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.server.port=8080
spring.servlet.context-path=/api/v1

spring.security.jwt.secret-key=pF+HxjF3FgXlI5nAzC/Nt+mv1T7PmZbOYfWcy6snYqE=
spring.security.jwt.expiration=600000